import type { SupplierAdapter, SupplierProductResult } from './SupplierAdapter';

const mockSupplierAProducts: SupplierProductResult[] = [
  {
    supplier: 'Juan Ferretería',
    location: 'Miami, US',
    productName: 'Hammer',
    productId: 'A-PROD-1001',
    category: 'Hand Tools',
    description: 'Forged steel claw hammer for general maintenance and construction tasks.',
    sku: 'HAM123',
    quantity: 20,
    price: 12.5,
    discountPercent: 3,
    stock: 20,
    delivery: '2 days',
    taxPercent: 7,
    amount: 259.25,
    source: 'mock',
    supplierAdapterId: 'mock-supplier-a',
  },
  {
    supplier: 'Juan Ferretería',
    location: 'Miami, US',
    productName: 'Drill',
    productId: 'A-PROD-1002',
    category: 'Power Tools',
    description: 'Compact electric drill with variable speed and impact mode.',
    sku: 'DRL456',
    quantity: 8,
    price: 54.99,
    discountPercent: 5,
    stock: 8,
    delivery: '3 days',
    taxPercent: 7,
    amount: 447.12,
    source: 'mock',
    supplierAdapterId: 'mock-supplier-a',
  },
  {
    supplier: 'Juan Ferretería',
    location: 'Orlando, US',
    productName: 'Screwdriver',
    productId: 'A-PROD-1003',
    category: 'Hand Tools',
    description: 'Magnetic tip screwdriver designed for assembly and repair work.',
    sku: 'SCR789',
    quantity: 35,
    price: 7.25,
    discountPercent: 2,
    stock: 35,
    delivery: '1 day',
    taxPercent: 7,
    amount: 266.12,
    source: 'mock',
    supplierAdapterId: 'mock-supplier-a',
  },
  {
    supplier: 'Juan Ferretería',
    location: 'Orlando, US',
    productName: 'Bolts',
    productId: 'A-PROD-1004',
    category: 'Fasteners',
    description: 'Zinc-coated industrial bolts suitable for general assembly operations.',
    sku: 'BLT159',
    quantity: 150,
    price: 0.35,
    discountPercent: 1,
    stock: 400,
    delivery: '2 days',
    taxPercent: 7,
    amount: 56.18,
    source: 'mock',
    supplierAdapterId: 'mock-supplier-a',
  },
  {
    supplier: 'Juan Ferretería',
    location: 'Tampa, US',
    productName: 'Nails',
    productId: 'A-PROD-1005',
    category: 'Fasteners',
    description: 'Galvanized nails packed for construction, carpentry, and repairs.',
    sku: 'NAL753',
    quantity: 300,
    price: 0.08,
    discountPercent: 0,
    stock: 1200,
    delivery: '2 days',
    taxPercent: 7,
    amount: 25.68,
    source: 'mock',
    supplierAdapterId: 'mock-supplier-a',
  },
  {
    supplier: 'Juan Ferretería',
    location: 'Miami, US',
    productName: 'Wrench',
    productId: 'A-PROD-1006',
    category: 'Mechanical Tools',
    description: 'Adjustable chrome wrench for mechanical maintenance and installation teams.',
    sku: 'WRN258',
    quantity: 14,
    price: 16.75,
    discountPercent: 4,
    stock: 24,
    delivery: '3 days',
    taxPercent: 7,
    amount: 250.75,
    source: 'mock',
    supplierAdapterId: 'mock-supplier-a',
  },
  {
    supplier: 'Juan Ferretería',
    location: 'Jacksonville, US',
    productName: 'Pliers',
    productId: 'A-PROD-1007',
    category: 'Hand Tools',
    description: 'Multi-purpose pliers with insulated grip for workshop and field tasks.',
    sku: 'PLR951',
    quantity: 18,
    price: 9.9,
    discountPercent: 2,
    stock: 31,
    delivery: '2 days',
    taxPercent: 7,
    amount: 190.60,
    source: 'mock',
    supplierAdapterId: 'mock-supplier-a',
  },
  {
    supplier: 'Juan Ferretería',
    location: 'Tampa, US',
    productName: 'Tape Measure',
    productId: 'A-PROD-1008',
    category: 'Measuring Tools',
    description: '5-meter tape measure with reinforced blade and lock mechanism.',
    sku: 'TPM357',
    quantity: 20,
    price: 6.8,
    discountPercent: 3,
    stock: 42,
    delivery: '2 days',
    taxPercent: 7,
    amount: 141.20,
    source: 'mock',
    supplierAdapterId: 'mock-supplier-a',
  },
  {
    supplier: 'Juan Ferretería',
    location: 'Miami, US',
    productName: 'Level',
    productId: 'A-PROD-1009',
    category: 'Measuring Tools',
    description: 'Aluminum level for alignment and framing applications.',
    sku: 'LVL852',
    quantity: 9,
    price: 18.4,
    discountPercent: 4,
    stock: 15,
    delivery: '4 days',
    taxPercent: 7,
    amount: 170.12,
    source: 'mock',
    supplierAdapterId: 'mock-supplier-a',
  },
  {
    supplier: 'Juan Ferretería',
    location: 'Orlando, US',
    productName: 'Saw',
    productId: 'A-PROD-1010',
    category: 'Cutting Tools',
    description: 'Hand saw with triple-ground teeth for wood and PVC cutting.',
    sku: 'SAW741',
    quantity: 11,
    price: 21.25,
    discountPercent: 5,
    stock: 17,
    delivery: '3 days',
    taxPercent: 7,
    amount: 237.36,
    source: 'mock',
    supplierAdapterId: 'mock-supplier-a',
  },
];

export class MockSupplierAAdapter implements SupplierAdapter {
  readonly id = 'mock-supplier-a';

  readonly supplierName = 'Juan Ferretería';

  async searchProduct(query: string): Promise<SupplierProductResult[]> {
    const normalizedQuery = String(query || '').trim().toLowerCase();

    return mockSupplierAProducts
      .filter((product) =>
        product.productName.toLowerCase().includes(normalizedQuery) ||
        product.sku.toLowerCase().includes(normalizedQuery) ||
        product.category.toLowerCase().includes(normalizedQuery),
      )
      .map((product) => ({
        ...product,
        source: 'mock',
        supplierAdapterId: this.id,
      }));
  }
}

export const mockSupplierAAdapter = new MockSupplierAAdapter();
