import type { SupplierAdapter, SupplierProductResult } from './SupplierAdapter';

const mockSupplierBProducts: SupplierProductResult[] = [
  {
    supplier: 'Pedro Centro de Cerámicas',
    location: 'Bogotá, CO',
    productName: 'Hammer',
    productId: 'B-PROD-2101',
    category: 'Industrial Tools',
    description: 'Heavy-duty hammer with anti-slip grip for warehouse and field use.',
    sku: 'HAM222',
    quantity: 12,
    price: 11,
    discountPercent: 4,
    stock: 12,
    delivery: '4 days',
    taxPercent: 19,
    amount: 150.86,
    source: 'mock',
    supplierAdapterId: 'mock-supplier-b',
  },
  {
    supplier: 'Pedro Centro de Cerámicas',
    location: 'Medellín, CO',
    productName: 'Saw',
    productId: 'B-PROD-2102',
    category: 'Cutting Tools',
    description: 'Professional hand saw with hardened teeth for wood cutting.',
    sku: 'SAW333',
    quantity: 16,
    price: 19.75,
    discountPercent: 6,
    stock: 16,
    delivery: '5 days',
    taxPercent: 19,
    amount: 355.97,
    source: 'mock',
    supplierAdapterId: 'mock-supplier-b',
  },
  {
    supplier: 'Pedro Centro de Cerámicas',
    location: 'Cali, CO',
    productName: 'Wrench',
    productId: 'B-PROD-2103',
    category: 'Mechanical Tools',
    description: 'Adjustable wrench for maintenance teams and workshop operations.',
    sku: 'WRN444',
    quantity: 10,
    price: 14.4,
    discountPercent: 3,
    stock: 10,
    delivery: '2 days',
    taxPercent: 19,
    amount: 166.32,
    source: 'mock',
    supplierAdapterId: 'mock-supplier-b',
  },
  {
    supplier: 'Pedro Centro de Cerámicas',
    location: 'Bogotá, CO',
    productName: 'Drill',
    productId: 'B-PROD-2104',
    category: 'Power Tools',
    description: 'Corded impact drill designed for commercial maintenance operations.',
    sku: 'DRL620',
    quantity: 7,
    price: 52.4,
    discountPercent: 4,
    stock: 11,
    delivery: '3 days',
    taxPercent: 19,
    amount: 416.13,
    source: 'mock',
    supplierAdapterId: 'mock-supplier-b',
  },
  {
    supplier: 'Pedro Centro de Cerámicas',
    location: 'Medellín, CO',
    productName: 'Screwdriver',
    productId: 'B-PROD-2105',
    category: 'Hand Tools',
    description: 'Precision screwdriver with ergonomic handle for daily repair tasks.',
    sku: 'SCR512',
    quantity: 24,
    price: 6.95,
    discountPercent: 2,
    stock: 60,
    delivery: '2 days',
    taxPercent: 19,
    amount: 198.31,
    source: 'mock',
    supplierAdapterId: 'mock-supplier-b',
  },
  {
    supplier: 'Pedro Centro de Cerámicas',
    location: 'Cali, CO',
    productName: 'Bolts',
    productId: 'B-PROD-2106',
    category: 'Fasteners',
    description: 'Industrial bolts packed for machinery support and light construction.',
    sku: 'BLT601',
    quantity: 200,
    price: 0.31,
    discountPercent: 3,
    stock: 650,
    delivery: '3 days',
    taxPercent: 19,
    amount: 71.62,
    source: 'mock',
    supplierAdapterId: 'mock-supplier-b',
  },
  {
    supplier: 'Pedro Centro de Cerámicas',
    location: 'Bogotá, CO',
    productName: 'Nails',
    productId: 'B-PROD-2107',
    category: 'Fasteners',
    description: 'Construction-grade nails available in high-volume commercial packs.',
    sku: 'NAL844',
    quantity: 350,
    price: 0.07,
    discountPercent: 0,
    stock: 1500,
    delivery: '2 days',
    taxPercent: 19,
    amount: 29.16,
    source: 'mock',
    supplierAdapterId: 'mock-supplier-b',
  },
  {
    supplier: 'Pedro Centro de Cerámicas',
    location: 'Medellín, CO',
    productName: 'Pliers',
    productId: 'B-PROD-2108',
    category: 'Hand Tools',
    description: 'Long-nose pliers ideal for electrical and precision work.',
    sku: 'PLR909',
    quantity: 13,
    price: 10.6,
    discountPercent: 3,
    stock: 26,
    delivery: '4 days',
    taxPercent: 19,
    amount: 159.82,
    source: 'mock',
    supplierAdapterId: 'mock-supplier-b',
  },
  {
    supplier: 'Pedro Centro de Cerámicas',
    location: 'Cali, CO',
    productName: 'Tape Measure',
    productId: 'B-PROD-2109',
    category: 'Measuring Tools',
    description: 'Durable tape measure suitable for warehouse counting and installations.',
    sku: 'TPM114',
    quantity: 19,
    price: 6.1,
    discountPercent: 2,
    stock: 35,
    delivery: '2 days',
    taxPercent: 19,
    amount: 136.37,
    source: 'mock',
    supplierAdapterId: 'mock-supplier-b',
  },
  {
    supplier: 'Pedro Centro de Cerámicas',
    location: 'Bogotá, CO',
    productName: 'Level',
    productId: 'B-PROD-2110',
    category: 'Measuring Tools',
    description: 'Compact spirit level for finishing work and alignment checks.',
    sku: 'LVL330',
    quantity: 10,
    price: 17.8,
    discountPercent: 4,
    stock: 19,
    delivery: '3 days',
    taxPercent: 19,
    amount: 203.25,
    source: 'mock',
    supplierAdapterId: 'mock-supplier-b',
  },
];

export class MockSupplierBAdapter implements SupplierAdapter {
  readonly id = 'mock-supplier-b';

  readonly supplierName = 'Pedro Centro de Cerámicas';

  async searchProduct(query: string): Promise<SupplierProductResult[]> {
    const normalizedQuery = String(query || '').trim().toLowerCase();

    return mockSupplierBProducts
      .filter((product) =>
        product.productName.toLowerCase().includes(normalizedQuery) ||
        product.sku.toLowerCase().includes(normalizedQuery) ||
        product.category.toLowerCase().includes(normalizedQuery),
      )
      .map((product) => ({
        ...product,
        source: 'mock',
        supplierAdapterId: this.id,
      }));
  }
}

export const mockSupplierBAdapter = new MockSupplierBAdapter();
